#Title: Abdelmalak-composers.yaml
#Author: Soliman Abdelmalak
#Date: 06/12/2021
#Description: Describing an API with description format

openapi: 3.0.1
info:
  title: Composer API
  version: 1.0.0
components:
  schemas:
    composer:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
tags:
  - name: Composers
paths:
  /Composers:
    #find All Composers
    get:
      tags:
        - Composers
      summary: returns list of composer documents
      description: API for returning list of composers from MongoDb Atlas
      operationId: findAllComposers
      #responses with description for 200, 500, and 501
      responses:
        '200':
          description: Composer documents
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
    #create a composer
    post:
      tags:
        - Composers
      summary: Creates a new composer object
      description: API for adding new composer objects
      operationId: createComposer
      requestBody:
        description: Composer's Information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/composer'
      #responses with description for 200, 500, and 501
      responses:
        '200':
          description: User added
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
  '/composers/{id}':
    # find a composer by Id
    get:
      tags:
        - Composers
      summary: Returns a composer document
      description: API for returning a single composer object from MongoDB
      operationId: findComposerById
      parameters:
        - name: id
          in: path
          description: The composerid requested by the user
          required: true
          schema: {}
      #responses with description for 200, 500, and 501
      responses:
        '200':
          description: Composer document in JSON format
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
